// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxzuhWnuW-uYjDKMu8SudbnL05fWlpes',
    appId: '1:733741196036:web:4ca2b73fcd0cdf7d44a651',
    messagingSenderId: '733741196036',
    projectId: 'medical-f6f5a',
    authDomain: 'medical-f6f5a.firebaseapp.com',
    storageBucket: 'medical-f6f5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwWxZpwTQ5cXBwMmUYCFXX3ddQJi0Ka2s',
    appId: '1:733741196036:android:8854ec338210bd4044a651',
    messagingSenderId: '733741196036',
    projectId: 'medical-f6f5a',
    storageBucket: 'medical-f6f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_gUoESZgCCPndDugYZj8dJevXQH_SPQ',
    appId: '1:733741196036:ios:b86e6c601bb3856f44a651',
    messagingSenderId: '733741196036',
    projectId: 'medical-f6f5a',
    storageBucket: 'medical-f6f5a.appspot.com',
    iosClientId: '733741196036-1for6erjo485ccto057258ko0m9aa6ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalHistory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_gUoESZgCCPndDugYZj8dJevXQH_SPQ',
    appId: '1:733741196036:ios:b86e6c601bb3856f44a651',
    messagingSenderId: '733741196036',
    projectId: 'medical-f6f5a',
    storageBucket: 'medical-f6f5a.appspot.com',
    iosClientId: '733741196036-1for6erjo485ccto057258ko0m9aa6ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalHistory',
  );
}
